language: ruby
cache: bundler
rvm:
  - 2.2.0
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script:
  - psql -c "CREATE USER dpk WITH PASSWORD 'dpk';" -U postgres
  - cp config/database.yml.travis config/database.yml